---
- name: Install nginx for Ubuntu
  apt:
    name: nginx
    state: present
  when: ansible_os_family == 'Debian'

- name: Install nginx for CentOS
  yum:
    name: nginx
    state: present
  when: ansible_os_family == 'RedHat'

- name: Enable and start service nginx
  systemd:
    name: nginx
    state: started
    enabled: true

- name: Setup nginx
  copy:
    src: '{{ item }}'
    dest: '/etc/nginx/{{ item }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - nginx.conf
    - nginx.php.conf
  notify:
    - reload nginx
