---
- name: restart postgresql
  action: systemd name=postgresql state=restarted
  when: ansible_os_family == 'Debian'

- name: restart postgresql
  action: systemd name=postgresql-9.4 state=restarted
  when: ansible_os_family == 'RedHat'
