---
- name: Add API endpoint host to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: 'api\five-final.isucon\.net'
    line: '{{api_host}} api.five-final.isucon.net'
    state: present

- name: Create .ssh
  file:
    path: /home/isucon/.ssh
    state: directory
    owner: isucon
    group: isucon
    mode: 0755
- name: Set deploy key
  copy:
    src: deploy_id_rsa
    dest: /home/isucon/.ssh/deploy_id_rsa
    owner: isucon
    group: isucon
    mode: 0600

- name: Git clone
  git:
    repo: git@github.com:tagomoris/isucon5-final.git
    dest: /tmp/isucon5-final
    key_file: /home/isucon/.ssh/deploy_id_rsa
    accept_hostkey: yes

- name: Setup webapp
  synchronize:
    src: /tmp/isucon5-final/webapp
    dest: /home/isucon/
    delete: yes
    rsync_opts:
      - --remove-source-files
  delegate_to: '{{ inventory_hostname }}'

# /home/isucon/webapp/{etc,go,java,nodejs,perl,php,python,ruby,scala,sql,static}
- name: Remove source dirs
  file:
    path: /tmp/isucon5-final
    state: absent

- name: Set env.sh
  copy:
    src: env.sh
    dest: /home/isucon/env.sh
    owner: isucon
    group: isucon
    mode: 0755

- name: ruby
  shell: PATH=/home/isucon/.local/ruby/bin:$PATH bundle install
  args:
    chdir: /home/isucon/webapp/ruby

- name: perl
  shell: PATH=/home/isucon/.local/perl/bin:$PATH carton install
  args:
    chdir: /home/isucon/webapp/perl

- name: php
  shell: PATH=/home/isucon/.local/php/bin:$PATH php composer.phar install
  args:
    chdir: /home/isucon/webapp/php

- name: node
  shell: PATH=/home/isucon/.local/node/bin:$PATH npm install
  args:
    chdir: /home/isucon/webapp/node

- name: java
  shell: ./mvnw clean package -Dmaven.test.skip=true
  args:
    chdir: /home/isucon/webapp/java

- name: Copy requirements.txt
  copy:
    src: requirements.txt
    dest: /tmp/requirements.txt
    owner: isucon
    group: isucon
    mode: 0755
- name: python
  command: /home/isucon/.local/python3/bin/pip install -r /tmp/requirements.txt

- name: go get pq
  shell: PATH=/home/isucon/.local/go/bin:$PATH GOROOT=/home/isucon/.local/go GOPATH=/home/isucon/webapp/golang go get github.com/lib/pq
  args:
    chdir: /home/isucon/webapp/golang
- name: go get context
  shell: PATH=/home/isucon/.local/go/bin:$PATH GOROOT=/home/isucon/.local/go GOPATH=/home/isucon/webapp/golang go get github.com/gorilla/context
  args:
    chdir: /home/isucon/webapp/golang
- name: go get mux
  shell: PATH=/home/isucon/.local/go/bin:$PATH GOROOT=/home/isucon/.local/go GOPATH=/home/isucon/webapp/golang go get github.com/gorilla/mux
  args:
    chdir: /home/isucon/webapp/golang
- name: go get sessions
  shell: PATH=/home/isucon/.local/go/bin:$PATH GOROOT=/home/isucon/.local/go GOPATH=/home/isucon/webapp/golang go get github.com/gorilla/sessions
  args:
    chdir: /home/isucon/webapp/golang
- name: go build
  shell: PATH=/home/isucon/.local/go/bin:$PATH GOROOT=/home/isucon/.local/go GOPATH=/home/isucon/webapp/golang go build -o app
  args:
    chdir: /home/isucon/webapp/golang

- name: scala
  shell: ./sbt launcher
  args:
    chdir: /home/isucon/webapp/scala

- name: Run initial query
  shell: cat ./initialize.sql | sudo -u isucon psql isucon5f
  args:
    chdir: /home/isucon/webapp/sql

- name: Install supervisor for Ubuntu
  apt:
    name: supervisor
    state: present
  when: ansible_os_family == 'Debian'

- name: Install supervisor for CentOS 7
  yum:
    name: supervisor
    state: present
    enablerepo: epel
  when: ansible_os_family == 'RedHat'

- name: Copy supervisor conf
  copy:
    src: 'supervisor.{{ item }}.conf'
    dest: '/etc/supervisor/conf.d/{{ item }}.conf'
  with_items:
    - ruby
    - perl
    - php
    - node
    - java
    - python
    - golang
    - scala

- name: Add to supervisorctl
  supervisorctl:
    name: '{{ item }}'
    state: present
  with_items:
    - ruby
    - perl
    - php
    - node
    - java
    - python
    - golang
    - scala

- name: default application
  supervisorctl:
    name: ruby
    state: restarted


