---
- name: Setup xbuild
  git:
    repo: https://github.com/tagomoris/xbuild.git
    dest: /home/isucon/.xbuild
    update: yes

- name: Install ruby
  command: /home/isucon/.xbuild/ruby-install 2.2.3 /home/isucon/.local/ruby
  args:
    creates: /home/isucon/.local/ruby/bin/ruby

- name: Install node
  command: /home/isucon/.xbuild/node-install v4.1.1 /home/isucon/.local/node
  args:
    creates: /home/isucon/.local/node/bin/node

- name: Install python
  command: /home/isucon/.xbuild/python-install 3.4.3 /home/isucon/.local/python3
  args:
    creates: /home/isucon/.local/python3/bin/python

- name: Install perl
  command: /home/isucon/.xbuild/perl-install 5.20.2 /home/isucon/.local/perl
  args:
    creates: /home/isucon/.local/perl/bin/perl

- name: Install php
  command: /home/isucon/.xbuild/php-install 5.6.13 /home/isucon/.local/php -- --with-pear --with-openssl --with-pdo-pgsql
  args:
    creates: /home/isucon/.local/php/bin/php

- name: Setup php.ini
  copy:
    src: php.ini
    dest: /home/isucon/.local/php/etc/php.ini
    owner: isucon
    group: isucon
    mode: 0644

- name: Install golang
  command: /home/isucon/.xbuild/go-install 1.8 /home/isucon/.local/go
  args:
    creates: /home/isucon/.local/go/bin/go

- name: Install scala
  shell: curl http://downloads.typesafe.com/scala/2.11.7/scala-2.11.7.tgz | (cd /home/isucon/.local && tar xzf -)
  args:
    creates: /home/isucon/.local/scala-2.11.7/bin/scala

- name: Create symlink to scala
  file:
    src: /home/isucon/.local/scala-2.11.7
    dest: /home/isucon/.local/scala
    state: link

- name: Add java repository
  apt_repository:
    repo: '{{ item }}'
  with_items:
    - 'ppa:webupd8team/java'
    - 'ppa:cwchien/gradle'
  when: ansible_os_family == 'Debian'

- name: Autoaccept license for Java8
  debconf:
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'
  when: ansible_os_family == 'Debian'

- name: Insall java
  apt:
    name: '{{ item }}'
    update_cache: yes
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default
    - ca-certificates
    - gradle-2.8
  when: ansible_os_family == 'Debian'

- name: Create symlink to java
  file:
    src: /usr/lib/jvm/java-8-oracle
    dest: /usr/lib/jvm/default-java
    owner: root
    group: root
    state: link
  when: ansible_os_family == 'Debian'
